image_root: C:/Users/tsake/OneDrive/Desktop/Aircraft_dataset/content/Aircraft_dataset
train_json: C:/Users/tsake/OneDrive/Desktop/Aircraft_dataset/content/Aircraft_dataset/Aircraft_train.json
val_json: C:/Users/tsake/OneDrive/Desktop/Aircraft_dataset/content/Aircraft_dataset/Aircraft_val.json
test_json: C:/Users/tsake/OneDrive/Desktop/Aircraft_dataset/content/Aircraft_dataset/Aircraft_test.json

class_names: configs/classes.txt
json_paths: []
