image_root: dataset/mild_data_1
train_json: dataset/mild_data_1/train.json
val_json: dataset/mild_data_1/valid.json
test_json: dataset/mild_data_1/test.json

class_names: configs/classes.txt
json_paths: []
